# Generated by Django 3.1.3 on 2020-11-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201129_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuspecs',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
