# Generated by Django 3.1.3 on 2020-11-29 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20201129_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storspecs',
            name='price_per_gb',
            field=models.DecimalField(decimal_places=3, max_digits=6, null=True),
        ),
    ]
