# Generated by Django 3.1.3 on 2020-11-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201129_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpuspecs',
            name='memory',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
